### ISSUE TITLE
Add option to set a default location, or accept location flag

### ISSUE THREAD

**Issue by joshfarrant** [ismaelgt/metaweather-cli#2]
Great work on this!

It's be nice if you could specify a default location or, alternately, if you could pass in a location name or `woeid` when you launch the tool.

**Comment by ismaelgt** [comment]
Thanks for creating this issue!

My idea is having two different modes:

- An interactive one which will ask questions about location, units (even provider in the future), etc. Something like `weather -i`.
- Also something with a more straight answer and a location based on IP: just `weather`.

The options in the interactive mode will also, ideally, be specified via command-line options. This will require a bit more thought.
